Write a function so that the columns of the output matrix are powers of the input vector. 
The order of the powers is determined by the increasing boolean argument. Specifically, when  increasing is False, the i-th output column is the input vector raised element-wise to the power  of N - i - 1. 
HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde. 


In [29]:
import numpy as np
a=[1,2,3,4,5]
arr=np.array(a)
print(arr)

[1 2 3 4 5]


In [38]:
b=np.array([arr])
b1=b.T
print(b1)
N=5
matrix=np.ones((5,5))
for i in range(N):
    mat=[b1**(N-i-1)]
    print(mat)
   


[[1]
 [2]
 [3]
 [4]
 [5]]
[array([[  1],
       [ 16],
       [ 81],
       [256],
       [625]], dtype=int32)]
[array([[  1],
       [  8],
       [ 27],
       [ 64],
       [125]], dtype=int32)]
[array([[ 1],
       [ 4],
       [ 9],
       [16],
       [25]], dtype=int32)]
[array([[1],
       [2],
       [3],
       [4],
       [5]], dtype=int32)]
[array([[1],
       [1],
       [1],
       [1],
       [1]], dtype=int32)]


In [39]:
import numpy as np
a=[1,2,3,4,5]
arr=np.array(a)
print(arr)

[1 2 3 4 5]


In [42]:
b=np.array([arr])
b1=b.T
print(b1)
N=5
matrix=np.ones((5,5))
matrix = np.column_stack([b1**(N-i-1) for i in range(N)])
print(matrix)

[[1]
 [2]
 [3]
 [4]
 [5]]
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


Question: Write a function to find moving average in an array over a window:  Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3. 

In [56]:
def moving_average(x, w):
    return np.convolve(x, np.ones(w), 'valid') / w

In [57]:
c=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] 
N=13
k=3
carr=np.array(c)
aq=moving_average(carr,3)
print(aq)

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]


def moving_average(x, w):
    return np.convolve(x, np.ones(w), 'valid') / w

In [55]:
np.ones(3)

array([1., 1., 1.])