In each of the following situations, state whether it is a correctly stated hypothesis
testing problem and why?
1. H0: μ = 25, H1: μ ≠ 25
2. H0: σ > 10, H1: σ = 10
3. H0: x = 50, H1: x ≠ 50
4. H0: p = 0.1, H1: p = 0.5
5. H0: s = 30, H1: s > 30

1.  H0: μ = 25, H1: μ ≠ 25
This is valid two tailed hypothesis, since alternate hypothesis is reverse of null hypothesis.
2. H0: σ > 10, H1: σ = 10
This is invalid hypothesis.
3. H0: x = 50, H1: x ≠ 50
This is valid two tailed hypothesis, since alternate hypothesis is reverse of null hypothesis.
4. H0: p = 0.1, H1: p = 0.5
This is invalid hypothesis, since alternate hypothesis is not reverse of null hypothesis.
5. H0: s = 30, H1: s > 30
This is valid hypothesis, for one sided test.(Right tailed test)

The college bookstore tells prospective students that the average cost of its
textbooks is Rs. 52 with a standard deviation of Rs. 4.50. A group of smart statistics
students thinks that the average cost is higher. To test the bookstore’s claim against
their alternative, the students will select a random sample of size 100. Assume that
the mean from their random sample is Rs. 52.80. Perform a hypothesis test at the
5% level of significance and state your decision.

In [1]:

#H0: u=52
#h1: u not equal to 52
import math
pop_mean=52
pop_sd=4.50
n=100
sam_mean=52.80
sig=0.05   #alpha=1-sig
n1=math.sqrt(n)
n2=pop_sd/n1
Z=(sam_mean-pop_mean)/n2
print("Z test value",Z)
import scipy.stats as st
alpha=1-sig/2
zc=st.norm.ppf(alpha)
print("zcritical value",zc)
if -zc< Z<zc:
    print("We accept Null hypothesis with Ho:")
    print("The average cost of books is",pop_mean)
else:
    print("We reject Null hypothesis with Ho:")
    print("The average cost of books is not",pop_mean)
        

Z test value 1.7777777777777715
zcritical value 1.959963984540054
We accept Null hypothesis with Ho:
The average cost of books is 52


A certain chemical pollutant in the Genesee River has been constant for several
years with mean μ = 34 ppm (parts per million) and standard deviation σ = 8 ppm. A
group of factory representatives whose companies discharge liquids into the river is
now claiming that they have lowered the average with improved filtration devices. A
group of environmentalists will test to see if this is true at the 1% level of
significance. Assume \ that their sample of size 50 gives a mean of 32.5 ppm.
Perform a hypothesis test at the 1% level of significance and state your decision.

In [2]:
# H0: u=34
# H1: u is not equal 34
import math
pop_mean=34
pop_sd=8
n=50
sam_mean=32.5
sig=0.01
n1=math.sqrt(n)
n2=pop_sd/n1
Z=(sam_mean-pop_mean)/n2
print("Zsquare value",Z)
import scipy.stats as st
alpha=1-sig/2           # 2 tail test
zc=st.norm.ppf(alpha)
print("zcritical",zc)
if -zc< Z<zc:
    print("We accept Null hypothesis with Ho:")
    print("There claim that they have lowered the average with improved filtration devices is true")
else:
    print("We reject Null hypothesis with Ho:")
    print("There claim that they have lowered the average with improved filtration devices is false")
        

Zsquare value -1.3258252147247767
2.5758293035489004
We accept Null hypothesis with Ho:
There claim that they have lowered the average with improved filtration devices is true


Based on population figures and other general information on the U.S. population,
suppose it has been estimated that, on average, a family of four in the U.S. spends
about $1135 annually on dental expenditures. Suppose further that a regional dental
association wants to test to determine if this figure is accurate for their area of
country. To test this, 22 families of 4 are randomly selected from the population in
that area of the country and a log is kept of the family’s dental expenditure for one
year. The resulting data are given below. Assuming, that dental expenditure is
normally distributed in the population, use the data and an alpha of 0.5 to test the
dental association’s hypothesis.
1008, 812, 1117, 1323, 1308, 1415, 831, 1021, 1287, 851, 930, 730, 699,
872, 913, 944, 954, 987, 1695, 995, 1003, 994

In [38]:
import math
import statistics
from scipy.stats import ttest_1samp
pop_mean=1135
sam=[1008, 812, 1117, 1323, 1308, 1415, 831, 1021, 1287, 851, 930, 730, 699,872, 913, 944, 954, 987, 1695, 995, 1003, 994]
n=len(sam)
sam_mean=statistics.mean(sam)
sam_sd=statistics.stdev(sam)
alpha=0.5
dof=n-1
n1=math.sqrt(n)
n2=sam_sd/n1
t=(sam_mean-pop_mean)/n2
print("tvalue using formula",t)
# using library:
ttest,pvalue=ttest_1samp(sam,pop_mean)
print("t and pvalue using library",ttest,pvalue)
import scipy
t1=scipy.stats.t.ppf(1-alpha/2, dof)
print("tscore",t1)

if -t1< ttest< t1:
    print("We accept Null hypothesis with Ho:")
    print("The average figure is accurate for their area of country.",pop_mean)
else:
    print("We reject Null hypothesis with Ho:")
    print("The average figure is not accurate for their area of country.",pop_mean)

tvalue using formula -2.023137479931484
t and pvalue using library -2.023137479931484 0.0559738319464585
tscore 0.6863519891164291
We reject Null hypothesis with Ho:
The average figure is not accurate for their area of country. 1135


In a report prepared by the Economic Research Department of a major bank the
Department manager maintains that the average annual family income on Metropolis
is $48,432. What do you conclude about the validity of the report if a random sample
of 400 families shows and average income of $48,574 with a standard deviation of
2000?

In [39]:
#H0: u=48432
#H1: u is not equal to 48432

pop_mean=48432
n=400
sam_mean=48574
sam_sd=2000
alpha=0.05   #assume

#sample sd is given, sample size<30...ttest
dof=n-1
n1=math.sqrt(n)
n2=sam_sd/n1
t=(sam_mean-pop_mean)/n2
print("tvalue using formula",t)
import scipy
t1=scipy.stats.t.ppf(1-alpha/2, dof)
print("tscore",t1)

if -t1<t<t1:
    print("We accept Null hypothesis with Ho:")
    print("The report by Economic Research Department is valid with population mean",pop_mean)
else:
    print("We reject Null hypothesis with Ho:")
    print("The report by Economic Research Department is invalid with population mean",pop_mean)

tvalue using formula 1.42
tscore 1.965927295920809
We accept Null hypothesis with Ho:
The report by Economic Research Department is valid with population mean 48432


Suppose that in past years the average price per square foot for warehouses in the
United States has been $32.28. A national real estate investor wants to determine
whether that figure has changed now. The investor hires a researcher who randomly
samples 19 warehouses that are for sale across the United States and finds that the
mean price per square foot is $31.67, with a standard deviation of $1.29. assume
that the prices of warehouse footage are normally distributed in population. If the
researcher uses a 5% level of significance, what statistical conclusion can be
reached? What are the hypotheses?

In [40]:
import math
pop_mean=32.28
n=19
sam_mean=31.67
sam_sd=1.29
sig=0.05
#as sample sd is given, use ttest
dof=n-1
n1=math.sqrt(n)
n2=sam_sd/n1
t=(sam_mean-pop_mean)/n2
print("tvalue using formula",t)
import scipy.stats
t1=scipy.stats.t.ppf(1-sig/2, dof)
print("tscore",t1)

if -t1<t<t1:
    print("We accept Null hypothesis with Ho:")
    print("The average price per square foot for warehouses in United States is",pop_mean)
    print("The average price per square foot for warehouses in the United States did not change")
else:
    print("We reject Null hypothesis with Ho:")
    print("The average price per square foot for warehouses in United States is not",pop_mean)

tvalue using formula -2.06118477175179
tscore 2.10092204024096
We accept Null hypothesis with Ho:
The average price per square foot for warehouses in United States is 32.28
The average price per square foot for warehouses in the United States did not change


Find the t-score for a sample size of 16 taken from a population with mean 10 when
the sample mean is 12 and the sample standard deviation is 1.5.

In [6]:
import math
n=16
pop_mean=10
sam_mean=12
sam_sd=1.5
sig=0.05     # alpha=0.05
dof=n-1
n1=math.sqrt(n)
n2=sam_sd/n1
t=(sam_mean-pop_mean)/n2
print("tvalue using formula",t)
import scipy
alpha=1-sig
t1=scipy.stats.t.ppf(alpha, dof)       
print("tscore",t1)



tvalue using formula 5.333333333333333
tscore 1.7530503556925547


Find the t-score below which we can expect 99% of sample means will fall if samples
of size 16 are taken from a normally distributed population.

In [6]:
import scipy

n=16
#1-alpha=0.99
alpha=1-0.99
df=n-1

t1=scipy.stats.t.ppf(alpha, df)                   # reads ttable using df and alpha
print("tscore",t1)




tscore -2.602480294995493


If a random sample of size 25 drawn from a normal population gives a mean of 60
and a standard deviation of 4, find the range of t-scores where we can expect to find
the middle 95% of all sample means. Compute the probability that (−t0.05 <t<t0.10).

In [15]:
n=25
dof=n-1
sam_mean=60
sam_sd=4
sig=0.05
import scipy
alpha=1-sig
t1=scipy.stats.t.ppf(1-sig/2, dof)       
print("tcritical",t1)
print("The range of Tscores",-t1,t1)
P=1-0.10-0.05
print("Probability that (−t0.05 <t<t0.10):",P)

tcritical 2.0638985616280205
The range of Tscores -2.0638985616280205 2.0638985616280205
Probability that (−t0.05 <t<t0.10): 0.85


Two-tailed test for difference between two population means
Is there evidence to conclude that the number of people travelling from Bangalore to
Chennai is different from the number of people travelling from Bangalore to Hosur in
a week, given the following:
Population 1: Bangalore to Chennai n1 = 1200
x1 = 452
s1 = 212
Population 2: Bangalore to Hosur n2 = 800
x2 = 523
s2 = 185

In [7]:
# as sd for pop is given,n>30, we perform ztest, two tailed
n1=1200
x1=452
s1=212
n2=800
x2=523
s2=185
import math
s=(s1**2/n1)+(s2**2/n2)
se=math.sqrt(s)
zval=(x1-x2)/se
print("ztest value",zval)
sig=0.05
#two tailed test

import scipy.stats as st
alpha=1-sig/2
p=st.norm.ppf(alpha)
print(p)
if -p<zval<p:
    print("Accept H0")
    print("H0: the number of people travelling from Bangalore to Chennai is different from the number of people travelling from Bangalore to Hosur in a week")
else:
    print("Reject H0")
    print("H1: the number of people travelling from Bangalore to Chennai is not different from the number of people travelling from Bangalore to Hosur in a week")

ztest value -7.926428526759299
1.959963984540054
Reject H0
H1: the number of people travelling from Bangalore to Chennai is not different from the number of people travelling from Bangalore to Hosur in a week


Is there evidence to conclude that the number of people preferring Duracell battery is
different from the number of people preferring Energizer battery, given the following:
Population 1: Duracell
n1 = 100
x1 = 308
s1 = 84
Population 2: Energizer
n2 = 100
x2 = 254
s2 = 67



In [20]:
n1 = 100
x1 = 308
s1 = 84
n2 = 100
x2 = 254
s2 = 67
#as n>30, use z test
#H0: Number of people using both batteries are different
#H1: Number of people using both batteries are same

import math
s=(s1**2/n1)+(s2**2/n2)
se=math.sqrt(s)
zval=(x1-x2)/se
print(zval)
sig=0.05
import scipy.stats as st
alpha=1-sig/2
p=st.norm.ppf(alpha)
print(p)
if -p<zval<p:
    print("Accept H0")
    print("H0: Number of people using both batteries are different")
else:
    print("Reject H0")
    print("H1:Number of people using both batteries are same")

5.025702668336442
1.959963984540054
Reject H0
H1:Number of people using both batteries are same


Pooled estimate of the population variance
Does the data provide sufficient evidence to conclude that average percentage
increase in the price of sugar differs when it is sold at two different prices?
Population 1: Price of sugar = Rs. 27.50 n1 = 14
x1 = 0.317%
s1 = 0.12%
Population 2: Price of sugar = Rs. 20.00 n2 = 9
x2 = 0.21%
s2 = 0.11%

In [18]:
#H0: average percentage increase in the price of sugar differs when it is sold at two different prices
#H1: average percentage does not increase in the price of sugar differs when it is sold at two different prices
p1=27.50
n1=14
x1=0.00317
s1=0.0012
p2=20.00
n2=9
x2=0.0021
s2=0.0011
p=p1-p2

df=n1+n2-2
# as sample size< 30, ttest
num=((n1-1)*(s1**2))+((n2-1)*(s2**2))
s12=math.sqrt(num/(df))
s=math.sqrt(1/n1+1/n2)
se=s12*s
print(s)
x=abs(x1-x2)
ttest=x/se
print("ttest value",ttest)
import scipy.stats
sig=0.05
t1=scipy.stats.t.ppf(1-sig/2, df)    #2 tailed
print("tscore",t1)
if -t1<ttest<t1:
    print("We accept Null hypothesis with Ho:")
    print("price of sugar increase")
else:
    print("We reject Null hypothesis with Ho:")
    print("price of sugar does not increase")

0.4272466296411038
ttest value 2.15355322387416
tscore 2.079613844727662
We reject Null hypothesis with Ho:
price of sugar does not increase



The manufacturers of compact disk players want to test whether a small price
reduction is enough to increase sales of their product. Is there evidence that the
small price reduction is enough to increase sales of compact disk players?
Population 1: Before reduction
n1 = 15
x1 = Rs. 6598 s1 = Rs. 844
Population 2: After reduction n2 = 12
x2 = RS. 6870
s2 = Rs. 669

In [22]:
import math
#H0: a small price reduction is enough to increase sales of CD players.
#H1: a small price reduction is not enough to increase sales of CD players.
n1 = 15
x1 = 6598 
s1 = 844
n2 = 12
x2 = 6870
s2 = 669
df=n1+n2-2
# as sample size< 30, ttest
num=((n1-1)*(s1**2))+((n2-1)*(s2**2))
s12=math.sqrt(num/(df))
s=math.sqrt(1/n1+1/n2)
se=s12*s
print(s)
x=abs(x1-x2)
ttest=x/se
print("ttest value",ttest)
import scipy.stats
sig=0.05
t1=scipy.stats.t.ppf(1-sig, df)    #1 tailed
print("tscore",t1)
if -t1<ttest<t1:
    print("We accept Null hypothesis with Ho:")
    print("a small price reduction is enough to increase sales of CD players.")
else:
    print("We reject Null hypothesis with Ho:")
    print("a small price reduction is NOT enough to increase sales of CD players.")

0.3872983346207417
ttest value 0.9098300343990459
tscore 1.7081407612518986
We accept Null hypothesis with Ho:
a small price reduction is enough to increase sales of CD players.


Comparisons of two population proportions when the hypothesized difference is zero
Carry out a two-tailed test of the equality of banks’ share of the car loan market in
1980 and 1995.
Population 1: 1980
n1 = 1000
x1 = 53
p 1 = 0.53
Population 2: 1985
n2 = 100
x2 = 43
p 2= 0.53

In [30]:
#given, hypnothsized difference=0; samples>30  Ztest
# 2 tailed test
n1 = 1000
n1=100    # assume n=100
x1 = 53
p1 = 0.53
n2 = 100
x2 = 43
p2= 0.43
import math
#H0: u1-u2=0
#H1: u1-u2!=0
pc=(x1+x2)/(n1+n2)
print(pc)
a=((1/n1)+(1/n2))
pc1=math.sqrt(pc*(1-pc)*a)
ztest=(p1-p2)/pc1
print("test",ztest)
sig=0.1
import scipy.stats as st
alpha=1-sig/2
zscore=st.norm.ppf(alpha)
print("zscore,",zscore)
if -zscore<ztest<zscore:
    print("Accept H0:u1-u2=0")
else:
    print("Reject H0")

0.48
test 1.4153462926807452
zscore, 1.6448536269514722
Accept H0:u1-u2=0


Carry out a one-tailed test to determine whether the population proportion of
traveler’s check buyers who buy at least $2500 in checks when sweepstakes prizes
are offered as at least 10% higher than the proportion of such buyers when no
sweepstakes are on.
Population 1: With sweepstakes
n1 = 300
x1 = 120
p = 0.40
Population 2: No sweepstakes n2 = 700
x2 = 140
p 2= 0.20

In [23]:
#p1 !=x1/n1 and p2!=x2/n2, smaple>30, ztest
#one tailed test
n1 = 300
x1 = 120
p1 = 0.40
n2 = 700
x2 = 140
p2= 0.20
pc=(x1+x2)/(n1+n2)
pc
num=(p1-p2)-0.10
print(num)
a=(p1*(1-p1))/n1
b=(p2*(1-p2))/n2
den=math.sqrt(a+b)
ztest=num/den
print(ztest)
sig=0.001
import scipy.stats as st
alpha=1-sig/2
zscore=st.norm.ppf(alpha)
print(zscore)
if ztest<zscore:
    print("Accept H0")
else:
    print("Reject H0")
    print(" we may conclude that the proportion of customers buying at least $2500 of travelers checks is at least 10% higher when sweepstakes are on.")

0.1
3.1180478223116177
3.2905267314919255
Accept H0


A die is thrown 132 times with the following results: Number turned up: 1, 2, 3, 4, 5, 6
Frequency: 16, 20, 25, 14, 29, 28
Is the die unbiased? Consider the degrees of freedom as p − 1.

In [21]:
#H0:The die is unbiased
#H1: The die is not unbiased
d=132
n=6
E=d/n   #expected frequency of each number
s=0
occur=[16, 20, 25, 14, 29, 28]
for i in occur:
    s1=i-E
    s2=s1*s1
    s2=s2/E
    s=s+s2
print("chi square value",s)
dof=n-1
sig=0.05
chiscore=scipy.stats.chi2.ppf(1-sig, dof)
print("chi score",chiscore)
if s<chiscore:
    print("Accept H0")
    print("The die is unbiased")
else:
    print("Reject H0")
    print("The die is not unbiased")

chi square value 9.0
chi score 11.070497693516351
Accept H0
The die is unbiased


In a certain town, there are about one million eligible voters. A simple random
sample of 10,000 eligible voters was chosen to study the relationship between
gender and participation in the last election. The results are summarized in the
following 2X2 (read two by two) contingency table:

We would want to check whether being a man or a woman (columns) is independent of
having voted in the last election (rows). In other words, is “gender and voting independent”?

In [3]:
#H0: Gender and voting is independent.
#H1: Gender and voting is NOT independent
#Chi square test
import numpy as np
A = np.array([[2792,3591],[1486,2131]])
print(A)
colsum=(np.sum(A,axis=0))
rowsum=(np.sum(A,axis=1))
tot=10000

#tot=np.array([rowsum,colsum])
#print(tot)
#totsum=(np.sum(tot))
#print(totsum)
E=[]
for i in rowsum:
    a=[]
    for j in colsum:
        v=i*j/tot
        a.append(v)
    E.append(a)
print(E)
print(type(E))
print(type(A))
s=0
for i in range(len(A)):
    for j in range(len(A[0])):
        temp=(A[i][j]-E[i][j])**2
        t1=temp/E[i][j]
        s=s+t1
print("Chi square value",s)    
dof=1   #(no of rows-1)*(no of col-1)
sig=0.05
import scipy.stats
chiscore=scipy.stats.chi2.ppf(1-sig, dof)
print("chi score",chiscore)
if s<chiscore:
    print("Accept H0")
    print("Gender and voting is independent.")
else:
    print("Reject H0")
    print("Gender and voting is NOT independent.")

[[2792 3591]
 [1486 2131]]
[[2730.6474, 3652.3526], [1547.3526, 2069.6474]]
<class 'list'>
<class 'numpy.ndarray'>
Chi square value 6.660455899328067
chi score 3.841458820694124
Reject H0
Gender and voting is NOT independent.


A sample of 100 voters are asked which of four candidates they would vote for in an
election. The number supporting each candidate is given below:

Do the data suggest that all candidates are equally popular? [Chi-Square = 14.96,
with 3 df, p 0.05 .

In [5]:
#H0: All candidates are equally popular
#H1: All candidates are not equally popular
d=100
n=4
E=d/n   #expected frequency of each number
s=0
occur=[41,19,24,16]
for i in occur:
    s1=i-E
    s2=s1*s1
    s2=s2/E
    s=s+s2
print("chi square value",s)
dof=n-1
sig=0.05
chiscore=scipy.stats.chi2.ppf(1-sig, dof)
print("chi score",chiscore)
if s<chiscore:
    print("Accept H0")
    print("All candidates are equally popular")
else:
    print("Reject H0")
    print("All candidates are not equally popular")

chi square value 14.959999999999999
chi score 7.814727903251179
Reject H0
All candidates are not equally popular


Children of three ages are asked to indicate their preference for three photographs of
adults. Do the data suggest that there is a significant relationship between age and
photograph preference? What is wrong with this study? [Chi-Square = 29.6, with 4
df: p < 0.05].

In [2]:
#H0: that there is a significant relationship between age and photograph preference
#H1: that there is no significant relationship between age and photograph preference?
#Chi square test
import numpy as np
A = np.array([[18,22,20],[2,28,40],[20,10,40]])
print(A)
colsum=(np.sum(A,axis=0))
rowsum=(np.sum(A,axis=1))
tot=np.sum(colsum)
print(tot)
E=[]
for i in rowsum:
    a=[]
    for j in colsum:
        v=i*j/tot
        a.append(v)
    E.append(a)
print(E)
print(type(E))
print(type(A))
s=0
for i in range(len(A)):
    for j in range(len(A[0])):
        temp=(A[i][j]-E[i][j])**2
        t1=temp/E[i][j]
        s=s+t1
print("Chi square value",s)    
df=(len(rowsum)-1)*(len(colsum)-1)
print(df)
sig=0.001
import scipy.stats
chiscore=scipy.stats.chi2.ppf(1-sig, df)
print("chi score",chiscore)
if s<chiscore:
    print("Accept H0")
    print("that there is a significant relationship between age and photograph preference")
else:
    print("Reject H0")
    print("that there is No significant relationship between age and photograph preference")

[[18 22 20]
 [ 2 28 40]
 [20 10 40]]
200
[[12.0, 18.0, 30.0], [14.0, 21.0, 35.0], [14.0, 21.0, 35.0]]
<class 'list'>
<class 'numpy.ndarray'>
Chi square value 29.603174603174608
4
chi score 18.46682695290317
Reject H0
that there is No significant relationship between age and photograph preference


Problem Statement 21:

A study of conformity using the Asch paradigm involved two conditions: one where
one confederate supported the true judgement and another where no confederate
gave the correct response.

Is there a significant difference between the "support" and "no support" conditions in the
frequency with which individuals are likely to conform? [Chi-Square = 19.87, with 1 df:
p < 0.05].

In [4]:
#H0: there a significant difference between the "support" and "no support" conditions
#H1: there NO significant difference between the "support" and "no support" conditions
#Chi square test
import numpy as np
A = np.array([[18,40],[32,10]])
print(A)
colsum=(np.sum(A,axis=0))
rowsum=(np.sum(A,axis=1))
tot=np.sum(colsum)
print(tot)
print(colsum)
E=[]
for i in rowsum:
    a=[]
    for j in colsum:
        v=i*j/tot
        a.append(v)
    E.append(a)
print(E)
y=0.5
s=0
for i in range(len(A)):
    for j in range(len(A[0])):
        temp=abs((A[i][j]-E[i][j]))-y
        temp1=temp**2
        t1=temp1/E[i][j]
        s=s+t1
print("Chi square value",s)    
dof=(len(rowsum)-1)*(len(colsum)-1)
print(dof)
sig=0.001
import scipy.stats
chiscore=scipy.stats.chi2.ppf(1-sig, dof)
#chiscore=19.87
print("chi score",chiscore)
if s<chiscore:
    print("Accept H0")
    print("there is a significant difference between the support and no support conditions")
else:
    print("Reject H0")
    print("there is a significant difference between the support and no support conditions")

[[18 40]
 [32 10]]
100
[50 50]
[[29.0, 29.0], [21.0, 21.0]]
Chi square value 18.10344827586207
1
chi score 10.827566170662733
Reject H0
there is a significant difference between the support and no support conditions


We want to test whether short people differ with respect to their leadership qualities
(Genghis Khan, Adolf Hitler and Napoleon were all stature-deprived, and how many midget
MP's are there?) The following table shows the frequencies with which 43 short people and
52 tall people were categorized as "leaders", "followers" or as "unclassifiable". Is there a
relationship between height and leadership qualities?
[Chi-Square = 10.71, with 2 df: p < 0.01].

In [6]:
import numpy as np
A = np.array([[12,32],[22,14],[9,6]])
print(A)
colsum=(np.sum(A,axis=0))
rowsum=(np.sum(A,axis=1))
tot=np.sum(colsum)
print(tot)
E=[]
for i in rowsum:
    a=[]
    for j in colsum:
        v=i*j/tot
        a.append(v)
    E.append(a)
print(E)
print(type(E))
print(type(A))
s=0
for i in range(len(A)):
    for j in range(len(A[0])):
        temp=(A[i][j]-E[i][j])**2
        t1=temp/E[i][j]
        s=s+t1
print("Chi square value",s) 
df=(len(rowsum)-1)*(len(colsum)-1)
print(df)
sig=0.01
import scipy.stats
chiscore=scipy.stats.chi2.ppf(1-sig, df)

print("chi score",chiscore)
if s<chiscore:
    print("Accept H0")
    print("that there is  a relationship between height and leadership qualities. ")
else:
    print("Reject H0")
    print("that there is No  a relationship between height and leadership qualities. ")


[[12 32]
 [22 14]
 [ 9  6]]
95
[[19.91578947368421, 24.08421052631579], [16.294736842105262, 19.705263157894738], [6.7894736842105265, 8.210526315789474]]
<class 'list'>
<class 'numpy.ndarray'>
Chi square value 10.712198008709638
2
chi score 9.21034037197618
Reject H0
that there is No  a relationship between height and leadership qualities. 


In [ ]:
Each respondent in the Current Population Survey of March 1993 was classified as
employed, unemployed, or outside the labor force. The results for men in California age 35-
44 can be cross-tabulated by marital status, as follows:
    Men of different marital status seem to have different distributions of labor force status. Or is
this just chance variation? (you may assume the table results from a simple random
sample.)

In [7]:
import numpy as np
A = np.array([[ 679,103,114 ],[63,10,20],[42,18,25]])
print(A)
colsum=(np.sum(A,axis=0))
rowsum=(np.sum(A,axis=1))
tot=np.sum(colsum)
print(tot)
E=[]

for i in rowsum:
    a=[]
    for j in colsum:
        v=i*j/tot
        a.append(v)
    E.append(a)
print(E)
print(type(E))
print(type(A))
s=0
for i in range(len(A)):
    for j in range(len(A[0])):
        temp=(A[i][j]-E[i][j])**2
        t1=temp/E[i][j]
        s=s+t1
print("Chi square value",s) 
df=(len(rowsum)-1)*(len(colsum)-1)
print(df)
sig=0.05
import scipy.stats
chiscore=scipy.stats.chi2.ppf(1-sig, df)

print("chi score",chiscore)
if s<chiscore:
    print("Accept H0")
    print("that there is  a relationship between height and leadership qualities. ")
else:
    print("Reject H0")
    print("that there is No  a relationship between height and leadership qualities. ")

[[679 103 114]
 [ 63  10  20]
 [ 42  18  25]]
1074
[[654.0633147113595, 109.28864059590316, 132.64804469273744], [67.88826815642459, 11.343575418994414, 13.768156424581006], [62.04841713221602, 10.36778398510242, 12.583798882681565]]
<class 'list'>
<class 'numpy.ndarray'>
Chi square value 31.61310319407798
4
chi score 9.487729036781154
Reject H0
that there is No  a relationship between height and leadership qualities. 


7: Fill in the blank spaces:
        

In [37]:
x1=48.5
x2=51.5
u=50
#assume 
sd=2.5
n=10
import math
den=sd/(math.sqrt(n))
z1=(x1-u)/den
z2=(x2-u)/den
import scipy.stats as st
zscore1=st.norm.cdf(z1)
zscore2=st.norm.cdf(-z2)
zscore=zscore1+zscore2
u11=52
z11=(x1-u11)/den
z22=(x2-u11)/den
zscore11=st.norm.cdf(z11)
zscore22=st.norm.cdf(z22)
beta1=zscore22-zscore11
u22=50.5
z11=(x1-u22)/den
z22=(x2-u22)/den
zscore11=st.norm.cdf(z11)
zscore22=st.norm.cdf(z22)
beta2=zscore22-zscore11
print("alpha beta @ u=52 beta @u=50.5",zscore,beta1,beta2)

x1=48
x2=52
u=50
#assume 
sd=2.5
n=10
import math
den=sd/(math.sqrt(n))
z1=(x1-u)/den
z2=(x2-u)/den
import scipy.stats as st
zscore1=st.norm.cdf(z1)
zscore2=st.norm.cdf(-z2)
zscore=zscore1+zscore2
u11=52
z11=(x1-u11)/den
z22=(x2-u11)/den
zscore11=st.norm.cdf(z11)
zscore22=st.norm.cdf(z22)
beta1=zscore22-zscore11
u22=50.5
z11=(x1-u22)/den
z22=(x2-u22)/den
zscore11=st.norm.cdf(z11)
zscore22=st.norm.cdf(z22)
beta2=zscore22-zscore11
print("alpha beta @ u=48 beta @u=52",zscore,beta1,beta2)
x1=48.81
x2=51.9
u=50
#assume 
sd=2.5
n=16
import math
den=sd/(math.sqrt(n))
z1=(x1-u)/den
z2=(x2-u)/den
import scipy.stats as st
zscore1=st.norm.cdf(z1)
zscore2=st.norm.cdf(-z2)
zscore=zscore1+zscore2
u11=52
z11=(x1-u11)/den
z22=(x2-u11)/den
zscore11=st.norm.cdf(z11)
zscore22=st.norm.cdf(z22)
beta1=zscore22-zscore11
u22=50.5
z11=(x1-u22)/den
z22=(x2-u22)/den
zscore11=st.norm.cdf(z11)
zscore22=st.norm.cdf(z22)
beta2=zscore22-zscore11
print("alpha beta @ u=48.81 beta @u=51.9",zscore,beta1,beta2)
x1=48.42
x2=51.8
u=50
#assume 
sd=2.5
n=16
import math
den=sd/(math.sqrt(n))
z1=(x1-u)/den
z2=(x2-u)/den
import scipy.stats as st
zscore1=st.norm.cdf(z1)
zscore2=st.norm.cdf(-z2)
zscore=zscore1+zscore2
u11=52
z11=(x1-u11)/den
z22=(x2-u11)/den
zscore11=st.norm.cdf(z11)
zscore22=st.norm.cdf(z22)
beta1=zscore22-zscore11
u22=50.5
z11=(x1-u22)/den
z22=(x2-u22)/den
zscore11=st.norm.cdf(z11)
zscore22=st.norm.cdf(z22)
beta2=zscore22-zscore11
print("alpha beta @ u=48.82 beta @u=51.8",zscore,beta1,beta2)

alpha beta @ u=52 beta @u=50.5 0.057779571123597204 0.26353985497284643 0.8913423764409649
alpha beta @ u=48 beta @u=52 0.011412036386001651 0.4999997899803012 0.9703275133092002
alpha beta @ u=48.81 beta @u=51.9 0.02963798283446237 0.4364403708344303 0.9840290241059673
alpha beta @ u=48.82 beta @u=51.8 0.007724093453430432 0.37448416019559994 0.9807998742327454


In [36]:
import statistics 
x=[52,50.5]
a=statistics.stdev(x)
print(a)

1.0606601717798212


alpha beta @ u=48.82 beta @u=51.8 0.002567302271521386 0.3580647843899773 0.9908738737626397
