Is gender independent of education level? A random sample of 395 people were
surveyed and each person was asked to report the highest education level they
obtained. The data that resulted from the survey is summarized in the following table:
High School Bachelors Masters Ph.d. Total
Female 60 54 46 41 201
Male 40 44 53 57 194
Total 100 98 99 98 395
Question: Are gender and education level dependent at 5% level of significance? In
other words, given the data collected above, is there a relationship between the
gender of an individual and the level of education that they have obtained?

In [15]:
import numpy as np
A = np.array([[60,54,46,41,201],[40,44,53,57,194],[100,98,99,98,395]])
              
print(A)
colsum=(np.sum(A,axis=0))
rowsum=(np.sum(A,axis=1))
tot=np.sum(colsum)
print(tot)
print(colsum)
E=[]
for i in rowsum:
    a=[]
    for j in colsum:
        v=i*j/tot
        a.append(v)
    E.append(a)
print(E)
s=0
for i in range(len(A)):
    for j in range(len(A[0])):
        temp=abs((A[i][j]-E[i][j]))
        temp1=temp**2
        t1=temp1/E[i][j]
        s=s+t1
print("Chi square value",s)    
#dof=(len(rowsum)-1)*(len(colsum)-1)
dof=3
print(dof)
sig=0.05
import scipy.stats
chiscore=scipy.stats.chi2.ppf(1-sig, dof)
print("chi score",chiscore)
if s<chiscore:
    print("Accept H0")
    print(" the education level does not depend on gender at a 5% level of significance.")
else:
    print("Reject H0")
    print(" The education level depends on gender at a 5% level of significance.")

[[ 60  54  46  41 201]
 [ 40  44  53  57 194]
 [100  98  99  98 395]]
1580
[200 196 198 196 790]
[[50.88607594936709, 49.868354430379746, 50.37721518987342, 49.868354430379746, 201.0], [49.11392405063291, 48.131645569620254, 48.62278481012658, 48.131645569620254, 194.0], [100.0, 98.0, 99.0, 98.0, 395.0]]
Chi square value 8.006066246262538
3
chi score 7.814727903251179
Reject H0
 The education level depends on gender at a 5% level of significance.


Using the following data, perform a oneway analysis of variance using α=.05. Write
up the results in APA format.

[Group1: 51, 45, 33, 45, 67]
[Group2: 23, 43, 23, 43, 45]
[Group3: 56, 76, 74, 87, 56]

In [38]:
import numpy as np
A = np.array([[51,23,56],[45,43,76],[33,23,74],[45,43,87],[67,45,56]])
n1=5
n2=5
n3=5
print(A)
colmean=(np.mean(A,axis=0))
print(colmean)
gm=np.mean(colmean)
print(A.shape[1])
de_meaned = A.copy()
de_meaned = de_meaned.astype(np.float)
sq_dev=de_meaned.copy()
for i in range(A.shape[1]):  # iterate over col
    a=colmean[i]
    de_meaned[:,i] = de_meaned[:,i] - float(a)
    sq_dev[:,i]=de_meaned[:,i]**2

print(de_meaned)

print(sq_dev)
tot_sd=np.sum(sq_dev,axis=0)
print(tot_sd)
num=np.sum(tot_sd)
den=n1+n2+n3-3
mean_within=num/den
print("mean_within",mean_within)
s1=0
for i in colmean:
    a1=n1*((i-gm)**2)
    s1=(s1+a1)
mean_bet=s1/(3-1)
print(mean_bet)
ftest=mean_bet/mean_within
print(ftest)
sswithin=num
ssbet=s1
sstot=sswithin+ssbet
print("ss total",sstot)
var=ssbet/sstot
print("var",var)
import scipy.stats
p_value = scipy.stats.f.cdf(ftest, 2, 12)
p_value=1-p_value
print(p_value)
alpha=0.05
if p_value < alpha:
    print("Reject Null Hypothesis")
else:
    print("Accept Null Hypothesis")
fcritical=scipy.stats.f.ppf(1-0.05,2,12)
print(fcritical)
print("f(2,12)",fcritical)

[[51 23 56]
 [45 43 76]
 [33 23 74]
 [45 43 87]
 [67 45 56]]
[48.2 35.4 69.8]
3
[[  2.8 -12.4 -13.8]
 [ -3.2   7.6   6.2]
 [-15.2 -12.4   4.2]
 [ -3.2   7.6  17.2]
 [ 18.8   9.6 -13.8]]
[[  7.84 153.76 190.44]
 [ 10.24  57.76  38.44]
 [231.04 153.76  17.64]
 [ 10.24  57.76 295.84]
 [353.44  92.16 190.44]]
[612.8 515.2 732.8]
mean_within 155.06666666666666
1511.4666666666665
9.747205503009457
ss total 4883.733333333333
var 0.61898001528885
0.003059754143443061
Reject Null Hypothesis
3.8852938346523933
f(2,12) 3.8852938346523933


Calculate F Test for given 10, 20, 30, 40, 50 and 5,10,15, 20, 25.
For 10, 20, 30, 40, 50:

In [29]:
import numpy as np
N=5
N1=np.array([10,20,30,40,50])
N2=np.array([5,10,15, 20, 25])
import statistics as st
xm1=st.mean(N1)
sd1=st.stdev(N1)
var1=sd1**2
xm2=st.mean(N2)
sd2=st.stdev(N2)
var2=sd2**2
print(var1,var2)
Ftest=var1/var2
print("Ftest value for 10,20,30,40,50",Ftest)

250.0 62.0
Ftest value for 10,20,30,40,50 4.032258064516129
